---
- name: manager01
  hostname: manager01.dev.local
  ip_addr: 192.168.56.11
  playbook: playbooks/swarm-init.yml
  cpu: 1
  memory: 2048
  disk_size: 10240

- name: manager02
  hostname: manager02.dev.local
  ip_addr: 192.168.56.12
  playbook: playbooks/swarm-join.yml
  cpu: 1
  memory: 2048
  disk_size: 10240

- name: manager03
  hostname: manager03.dev.local
  ip_addr: 192.168.56.13
  playbook: playbooks/swarm-join.yml
  cpu: 1
  memory: 2048
  disk_size: 10240