---

- name: Setting master using a variable to hold a more complicate script
  set_fact:
    create_dsl_job: "{{ lookup('template', './dsl-job.j2') }}"
  
- name: use the variable as the script
  jenkins_script:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    script: "{{ create_dsl_job }}"
