---

- name: Create partitions and mount drives
  include: partitions.yml

- name: Install Jenkins
  include: install.yml

- name: Configure Jenkins
  include: settings.yml

- name: Bootstrap Jenkins
  include: bootstrap.yml

- name: Install plugins
  include: plugins.yml

- name: Create DSL job
  include: create_dsl_job.yml