---

- name: Install Jenkins
  include: install.yml

- name: Configure Jenkins
  include: settings.yml

- name: Bootstrap Jenkins
  include: bootstrap.yml

- name: Install plugins
  include: plugins.yml