---

- name: Check if jenkins_init_file exists.
  stat:
    path: "{{ jenkins_init_file }}"
  register: jenkins_init_file_stat

- name: Ensure jenkins_init_file exists.
  file:
    path: "{{ jenkins_init_file }}"
    state: touch
  when: not jenkins_init_file_stat.stat.exists

- name: Modify variables in init file.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^{{ item.option }}='
    regexp: '^{{ item.option }}=\"\${{ item.option }} '
    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    state: present
  with_items: "{{ jenkins_init_changes }}"
  register: jenkins_init_prefix

- name: Set the Jenkins home directory.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_HOME=.*'
    line: 'JENKINS_HOME={{ jenkins_home }}'
  register: jenkins_home_config

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: true
    dest: "{{ jenkins_init_file }}"
    regexp: '^HTTP_PORT='
    line: 'HTTP_PORT={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Immediately restart Jenkins on http or user changes.
  service:
    name: jenkins
    state: restarted
  when: >
    (jenkins_init_prefix is defined and jenkins_init_prefix.changed)
    or (jenkins_home_config is defined and jenkins_home_config.changed)
    or (jenkins_http_config is defined and jenkins_http_config.changed)

- name: Wait for Jenkins to start up
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    status_code: '200'
    timeout: 5
    force_basic_auth: yes
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
  register: jenkins_service_status
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status['status'] == 200
  when: >
    (jenkins_init_prefix is defined and jenkins_init_prefix.changed)
    or (jenkins_home_config is defined and jenkins_home_config.changed)
    or (jenkins_http_config is defined and jenkins_http_config.changed)