- hosts: all
  become: yes
  roles:
    - pogosoftware.lvm
    - pogosoftware.docker
  vars:
    vgs:
    - vg: data
      pvs: /dev/sdc
      lvs:
      - lv: docker
        size: +100%VG
        path: /var/lib/docker

    docker:
      install_docker_compose: yes
      docker_compose_version: '1.24.1'
      users:
        - vagrant