- name: Add DOCKER repo key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  tags:
    - docker

- name: Add DOCKER repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
    filename: docker
  tags:
    - docker

- name: Install docker
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: present
  tags:
    - docker

- name: Add the user 'vagrant' to a primary group of 'docker'
  user:
    name: vagrant
    comment: vagrant
    group: docker
  tags:
    - docker

- name: Ensure DOCKER is started and runs on startup.
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker