---

- name: Get Docker info
  shell: docker info
  register: docker_info

- name: Create primary swarm manager
  shell: docker swarm init --advertise-addr {{ manager_leader_ip_addr }}
  when: "docker_info.stdout.find('Swarm: inactive') != -1"

